#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/Geffen_mnist/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/geffen_faces/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/geffen_face_classifier/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/Geffen_Camera_Interface/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/geffen_regression/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/mnist/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/kws20_demo/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/geffen_bb/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/geffnet/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/face_classifier/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/HiLetgo_ILI9341/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/SPI/build/max78000.elf verify reset exit"
#sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts
sudo ./openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s ./scripts -c "program ../../Examples/MAX78000/CNN/mini_vgg_face_classifier/build/max78000.elf verify reset exit"
